[tool.pytest.ini_options]
testpaths = ["accounts", "tracker"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--verbose",
    "--tb=short",
    "--strict-markers",
    "--strict-config",
    "--ds=taskboard.settings",
    "--cov=.",
    "--cov-report=term-missing",
    "--cov-report=html",
    "--cov-fail-under=80"
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: integration tests",
    "unit: unit tests"
]

[tool.coverage.run]
source = ["accounts", "tracker"]
omit = [
    "*/migrations/*",
    "*/tests/*",
    "*/admin.py",
    "*/apps.py"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __str__",
    "raise AssertionError",
    "raise NotImplementedError"
]

[tool.ruff]
line-length = 79
select = ["E", "F", "I", "B", "C4"]
exclude = [
    "migrations",
    "manage.py",
]

ignore = [
    "E501","B008","C901",
]

target-version = "py311"

