# Generated by Django 5.2.4 on 2025-09-11 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_trackergroup_group_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='target_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='tracker.trackergroup'),
            preserve_default=False,
        ),
    ]
